/* ============================================================
   Beamerij — language switcher (NL / FR / EN)
   Client-side i18n. Dutch is the source; FR and EN are below.
   Choice is saved in localStorage; ?lang=fr|en and browser
   language are honoured on first visit.
   ============================================================ */
(function () {
  var SUPPORTED = ['nl', 'fr', 'en'];
  var STORE = 'beamerij-lang';

  var DICT = {
    nl: {
      'meta.title': 'Beamerij | Beamer & groot scherm huren in Antwerpen — 4K big-screen verhuur',
      'meta.desc': 'Beamerij verhuurt premium 4K beamers, een 200+ inch projectiescherm en complete big-screen sets in Antwerpen e.o. Voor filmavonden, voetbal, gaming, huwelijken en bedrijfsevents. Levering en opbouw mogelijk.',
      'skip': 'Ga naar inhoud',
      'announce.aria': 'WK 2026 — reserveer je matchday-set',
      'announce.text': '<b>WK&nbsp;2026 is bezig</b> — kijk elke match op een scherm van 6&nbsp;meter. Reserveer je matchday-set.',
      'announce.cta': 'Datum checken →',
      'nav.menu': 'Menu openen',
      'nav.occasions': 'Gelegenheden',
      'nav.packages': 'Pakketten',
      'nav.how': 'Hoe het werkt',
      'nav.faq': 'FAQ',
      'nav.contact': 'Contact',
      'nav.cta': 'Offerte aanvragen <span aria-hidden="true">↗</span>',
      'hero.eyebrow': 'Premium beamerverhuur in Antwerpen',
      'hero.title': 'Groot beeld.<br><em>Elk moment</em> bijzonder.',
      'hero.copy': 'Eén indrukwekkende 4K-set met een scherm van 200+ inch. Voor filmavonden, voetbal, gaming, huwelijken en bedrijfsevents. Wij leveren, bouwen op en ruimen weer op — jij geniet.',
      'hero.cta1': 'Check je datum <span aria-hidden="true">↗</span>',
      'hero.cta2': 'WhatsApp ons',
      'hero.trust1': '<strong>4K</strong> messcherp beeld',
      'hero.trust2': '<strong>200+ inch</strong> groot scherm',
      'hero.trust3': '<strong>Turnkey</strong> geleverd &amp; opgebouwd',
      'hero.trust4': '<strong>Geen btw</strong> alles inbegrepen',
      'hero.scrollaria': 'Scroll naar gelegenheden',
      'hero.scroll': 'Ontdek',
      'marquee': '<span>Filmavonden</span><i>✦</i><span>Voetbal &amp; WK 2026</span><i>✦</i><span>Gaming &amp; esports</span><i>✦</i><span>Huwelijken</span><i>✦</i><span>Bedrijfsevents</span><i>✦</i><span>Communie &amp; verjaardag</span><i>✦</i><span>Eindejaar</span><i>✦</i><span>Home cinema</span><i>✦</i><span>Filmavonden</span><i>✦</i><span>Voetbal &amp; WK 2026</span><i>✦</i><span>Gaming &amp; esports</span><i>✦</i><span>Huwelijken</span><i>✦</i><span>Bedrijfsevents</span><i>✦</i><span>Communie &amp; verjaardag</span><i>✦</i><span>Eindejaar</span><i>✦</i><span>Home cinema</span><i>✦</i>',
      'occ.eyebrow': 'Voor elk seizoen, elke setting',
      'occ.title': 'Eén scherm.<br><em>Oneindig veel</em> momenten.',
      'occ.intro': 'Van een zwoele filmavond tot een knotsgekke WK-avond: onze premium set maakt van elke bijeenkomst een ervaring om over na te praten. Altijd voor privégebruik of een intern bedrijfsevent.',
      'occ.tag': 'Topper',
      'occ.1.k': '01 — Zwoele zomeravonden', 'occ.1.t': 'Voetbal &amp; WK 2026', 'occ.1.d': 'Het stadiongevoel, gewoon op je eigen terras of in de tuin.',
      'occ.2.k': '02 — Ready player one', 'occ.2.t': 'Gaming &amp; esports', 'occ.2.d': '4K-beeld en lage inputlag: groot spelen zonder compromis.',
      'occ.3.k': '03 — Een grote dag', 'occ.3.t': 'Huwelijken &amp; feesten', 'occ.3.d': "Foto's, video en sfeerbeelden die je gasten raken.",
      'occ.4.k': '04 — Intern bedrijfsevent', 'occ.4.t': "Presentaties &amp; gala's", 'occ.4.d': 'Town halls, launches en awards met zichtbaar verschil.',
      'occ.5.k': '05 — Samen supporteren', 'occ.5.t': 'Sport in de tuin', 'occ.5.d': 'Vrienden, drankjes en de match op groot scherm onder de sterren.',
      'occ.6.k': '06 — Privé in de tuin', 'occ.6.t': 'Tuincinema &amp; filmavonden', 'occ.6.d': 'Film, dekens, vrienden en een scherm dat iedereen bijblijft.',
      'occ.foot': 'Ook voor <strong>communie &amp; lentefeest</strong>, <strong>verjaardagen</strong>, <strong>Sinterklaas &amp; eindejaar</strong> en een <strong>indoor home cinema</strong>. <a href="#contact" class="text-link">Vertel ons jouw plan <span>→</span></a>',
      'usp.1.t': 'Echt groot beeld', 'usp.1.d': 'Een opblaasbaar scherm van 200+ inch en een 4K-laserprojector van ca. 5.700 lumen. Helder, ook bij schemer.',
      'usp.2.t': 'Volledig ontzorgd', 'usp.2.d': 'Levering, opbouw, bediening en ophaling mogelijk. Jij hoeft niets te sleuren of in te stellen.',
      'usp.3.t': 'Lokaal &amp; persoonlijk', 'usp.3.d': 'Gevestigd in Antwerpen. Korte lijnen, persoonlijk contact en meestal antwoord binnen één werkdag.',
      'usp.4.t': 'Eén heldere prijs', 'usp.4.d': 'Vrijgesteld van btw. Wat je ziet, betaal je — alles inbegrepen, geen verrassingen achteraf.',
      'pkg.eyebrow': 'Helder geprijsd',
      'pkg.title': 'Kies hoeveel<br><em>ontzorging</em> je wil.',
      'pkg.intro': 'Alle prijzen zijn eindprijzen. Beamerij is vrijgesteld van btw: geen verrassingen, wel een volledig pakket.',
      'pkg.seo': 'Een beamer huren in Antwerpen, een groot scherm of projectiescherm huren, of meteen beamer en scherm huren voor een private outdoor cinema: je krijgt één premium oplossing. Ook een opblaasbaar scherm huren kan volledig zorgeloos.',
      'pkg.from': 'vanaf', 'pkg.night': '/ avond', 'pkg.featured': 'Meest gekozen',
      'pkg.avail': 'Vraag beschikbaarheid <span>→</span>', 'pkg.quote': 'Vraag je offerte <span>→</span>', 'pkg.discuss': 'Bespreek je event <span>→</span>',
      'pkg.1.label': 'Compact', 'pkg.1.t': 'Alleen beamer', 'pkg.1.d': 'Voor wie zelf een scherm of witte wand heeft.', 'pkg.1.sub': '€ 100 / weekend', 'pkg.1.f1': '4K laserprojector', 'pkg.1.f2': 'Kabels, afstandsbediening &amp; stroom', 'pkg.1.f3': 'Ophalen op afspraak',
      'pkg.2.label': 'De complete set', 'pkg.2.t': 'Full big-screen set', 'pkg.2.d': 'Jouw eigen spectaculaire cinema of viewing party.', 'pkg.2.sub': '€ 250 / weekend', 'pkg.2.f1': '200+ inch opblaasbaar projectiescherm + blower', 'pkg.2.f2': '4K projector, geluid &amp; stands', 'pkg.2.f3': 'Heldere self-setup briefing',
      'pkg.3.label': 'Volledig zorgeloos', 'pkg.3.t': 'Full-service event', 'pkg.3.d': 'Van aankomst tot afbouw: jij hoeft niets te doen.', 'pkg.3.sub': 'Antwerpen + 15 km', 'pkg.3.f1': 'Alles uit pakket B', 'pkg.3.f2': 'Levering, opbouw &amp; ophaling', 'pkg.3.f3': 'Bediening tijdens je event',
      'pkg.4.label': 'Op maat', 'pkg.4.t': 'Business &amp; meerdaags', 'pkg.4.d': 'Voor interne events, meerdaagse huur of extra technische noden.', 'pkg.4.sub': 'prijs op aanvraag', 'pkg.4.f1': 'Technische afstemming vooraf', 'pkg.4.f2': 'Flexibele huurperiode', 'pkg.4.f3': 'Extra begeleiding mogelijk',
      'pkg.note1': "<strong>Handige extra's</strong><br>Levering, opbouw &amp; ophaling € 50–80 · Operator ter plaatse (pakket A &amp; B) € 100–125 · Extra speaker of bekabeling € 15–25",
      'pkg.note2': '<strong>Waarborg</strong><br>Beamer € 300–400 · Full set € 500–750, of identiteitskaart + ondertekende overeenkomst.',
      'pkg.note3': '<strong>Alles inbegrepen, geen btw</strong><br>Je ziet meteen wat je betaalt. Geen btw wordt aangerekend.',
      'proc.eyebrow': 'Zo eenvoudig is het',
      'proc.title': 'Van idee naar<br><em>kippenvel.</em>',
      'proc.1.t': 'Aanvraag', 'proc.1.d': 'Vertel ons wanneer, waar en waarvoor je het scherm wil inzetten.',
      'proc.2.t': 'Bevestiging', 'proc.2.d': 'Je krijgt snel een helder voorstel met alle praktische afspraken.',
      'proc.3.t': 'Wij leveren &amp; installeren', 'proc.3.d': 'Bij full-service zetten we alles veilig en perfect op zijn plaats.',
      'proc.4.t': 'Jij geniet. Wij halen op.', 'proc.4.d': 'Na een onvergetelijke avond nemen wij de afbouw weer uit handen.',
      'specs.eyebrow': 'Wat zit erbij?',
      'specs.title': 'Alles voor een<br><em>indrukwekkend</em> beeld.',
      'specs.intro': 'Geen losse puzzelstukken. Onze set is zorgvuldig gekozen om binnen én buiten een groots moment neer te zetten.',
      'specs.caption': 'Één premium set. Volledig afgestemd.',
      'specs.1': 'Opblaasbaar projectiescherm met stille blower',
      'specs.2': 'Laserprojector van ca. 5.700 lumen, ook bij schemer helder',
      'specs.3.t': 'Audio', 'specs.3': 'Krachtige geluidsset met alle nodige bekabeling',
      'specs.4.t': 'Flexibel', 'specs.4': 'Voor tuin, terras, feestzaal, living of bedrijfsruimte',
      'specs.weather': '<strong>Goed om te weten:</strong> buitenopstellingen zijn weersafhankelijk. Bij regen of stevige wind zoeken we samen tijdig naar een veilige oplossing.',
      'atmo.eyebrow': 'Groot beeld, grote herinneringen',
      'atmo.title': 'Sommige avonden<br><em>blijven plakken.</em>',
      'atmo.copy': 'Een scherp beeld van 200+ inch verandert een gewone avond in iets waar je gasten nog maanden over praten. Wij zorgen voor de techniek. Jij voor het moment.',
      'atmo.cta': 'Reserveer jouw avond <span aria-hidden="true">↗</span>',
      'area.eyebrow': 'Lokaal en dichtbij',
      'area.title': 'Antwerpen<br><em>en omstreken.</em>',
      'area.copy': 'Full-service levering en opbouw in Antwerpen en binnen ongeveer 15 km. Verder weg? Vraag gerust, dan bekijken we wat mogelijk is.',
      'faq.eyebrow': 'Eerst even weten',
      'faq.title': 'Veelgestelde<br><em>vragen.</em>',
      'faq.intro': 'Staat je vraag er niet bij? Stuur ons een bericht, dan denken we concreet met je mee.',
      'faq.link': 'Neem contact op <span>→</span>',
      'faq.1.q': 'Leveren jullie ook?', 'faq.1.a': 'Ja. Bij full-service leveren, bouwen en halen we op in Antwerpen en de omliggende gemeenten. De levering is ook als extra bij andere pakketten mogelijk.',
      'faq.2.q': 'Hoe lang duurt de opbouw?', 'faq.2.a': 'Reken doorgaans op 30 tot 60 minuten, afhankelijk van de locatie en de gewenste opstelling. We plannen dit altijd ruim voor de start van je event.',
      'faq.3.q': 'Wat als het regent of hard waait?', 'faq.3.a': 'Veiligheid komt eerst. Bij ongeschikt weer bekijken we vooraf een binnenalternatief, een nieuw moment of een andere passende oplossing.',
      'faq.4.q': 'Hoe werkt de waarborg?', 'faq.4.a': 'De waarborg bedraagt € 300–400 voor alleen de beamer en € 500–750 voor de full set. In sommige gevallen kan dit ook met een identiteitskaart en ondertekende overeenkomst.',
      'faq.5.q': 'Wat bij schade, verlies of diefstal?', 'faq.5.a': 'De huurder is verantwoordelijk voor de set vanaf ontvangst tot ophaling. Schade, verlies of diefstal wordt volgens de huurvoorwaarden verrekend.',
      'faq.6.q': 'Kan ik annuleren?', 'faq.6.a': 'Dat kan volgens de afspraken in onze algemene voorwaarden. Omdat we een datum voor je reserveren, kunnen annuleringskosten gelden wanneer de annulering dicht bij het event gebeurt.',
      'faq.7.q': 'Kan de set binnen én buiten?', 'faq.7.a': 'Ja. Een tuin of terras is mooi, maar ook in een living, feestzaal of kantoorruimte maken we een indrukwekkende projectie. We stemmen de opstelling af op je ruimte.',
      'faq.8.q': 'Wat hebben jullie nodig qua stroom?', 'faq.8.a': 'Een normaal, veilig stopcontact in de buurt is meestal voldoende. Laat vooraf weten als de afstand groot is of als er geen stroomvoorziening op de locatie is.',
      'contact.eyebrow': 'Jouw datum, jouw moment',
      'contact.title': 'Maak het<br><em>onvergetelijk.</em>',
      'contact.copy': 'Vraag vrijblijvend je datum aan. We antwoorden snel met beschikbaarheid en een voorstel dat past bij je plan.',
      'contact.phone': 'Bel ons even',
      'contact.response': 'Meestal antwoord binnen 1 werkdag.',
      'contact.a1': 'Vrijblijvend &amp; gratis offerte', 'contact.a2': 'Persoonlijk advies op maat van je event', 'contact.a3': 'Geen btw — alles inbegrepen',
      'form.name': 'Naam', 'form.email': 'E-mail', 'form.phone': 'Telefoon', 'form.date': 'Datum event',
      'form.datehint': 'Nog niet zeker? Geef gerust een richtdatum.',
      'form.location': 'Locatie / postcode', 'form.package': 'Gewenst pakket', 'form.choose': 'Kies een pakket', 'form.unsure': 'Ik ben nog niet zeker',
      'form.message': 'Vertel kort iets over je event', 'form.placeholder': 'Bijvoorbeeld: filmavond voor 25 personen, opbouw in de tuin…',
      'form.consent': 'Door te versturen ga je akkoord met ons <a href="privacybeleid.html">privacybeleid</a>.',
      'form.submit': 'Vraag offerte aan <span aria-hidden="true">↗</span>',
      'form.successtitle': 'Bedankt voor je aanvraag.',
      'form.successbody': 'Je hoort meestal binnen 1 werkdag van ons. Snel nodig — bijvoorbeeld voor een WK-match dit weekend? Stuur ons gerust een <a href="https://wa.me/32XXXXXXXXX?text=Hoi%20Beamerij%2C%20ik%20heb%20net%20een%20aanvraag%20gedaan%20en%20het%20is%20wat%20dringend." target="_blank" rel="noopener noreferrer">WhatsApp</a>.',
      'form.sending': 'Even versturen…',
      'form.notconfigured': 'De formulierkoppeling is nog niet ingesteld. Mail ons intussen via info@beamerij.be.',
      'form.error': 'Versturen lukte niet. Probeer opnieuw of mail ons rechtstreeks via info@beamerij.be.',
      'footer.tagline': 'Premium big-screen rental voor momenten die mogen binnenkomen.',
      'footer.cta': 'Offerte aanvragen <span>↗</span>',
      'footer.nav': 'Navigatie', 'footer.call': 'Bel ons', 'footer.book': 'Datum aanvragen',
      'footer.region': 'Regio', 'footer.regionbody': 'Antwerpen + 15 km<br>Daarbuiten op aanvraag',
      'footer.vat': 'Kleine onderneming onderworpen aan de vrijstellingsregeling van btw - btw niet van toepassing.',
      'footer.privacy': 'Privacybeleid', 'footer.cookies': 'Cookiebeleid', 'footer.terms': 'Algemene voorwaarden', 'footer.cookieprefs': 'Cookievoorkeuren',
      'footer.rights': 'Alle rechten voorbehouden.',
      'float.aria': 'Stuur Beamerij een WhatsAppbericht', 'float.chat': 'Chat met ons',
      'totop.aria': 'Terug naar boven'
    },
    fr: {
      'meta.title': 'Beamerij | Location de projecteur & grand écran à Anvers — location big-screen 4K',
      'meta.desc': 'Beamerij loue des projecteurs 4K premium, un écran de projection 200+ inch et des sets big-screen complets à Anvers et alentours. Pour soirées cinéma, football, gaming, mariages et événements d\'entreprise. Livraison et installation possibles.',
      'skip': 'Aller au contenu',
      'announce.aria': 'Coupe du Monde 2026 — réservez votre set matchday',
      'announce.text': '<b>La Coupe du Monde&nbsp;2026 a commencé</b> — regardez chaque match sur un écran de 6&nbsp;mètres. Réservez votre set matchday.',
      'announce.cta': 'Vérifier la date →',
      'nav.menu': 'Ouvrir le menu',
      'nav.occasions': 'Occasions',
      'nav.packages': 'Formules',
      'nav.how': 'Comment ça marche',
      'nav.faq': 'FAQ',
      'nav.contact': 'Contact',
      'nav.cta': 'Demander un devis <span aria-hidden="true">↗</span>',
      'hero.eyebrow': 'Location de projecteurs premium à Anvers',
      'hero.title': 'Grande image.<br><em>Chaque moment</em> d\'exception.',
      'hero.copy': 'Un set 4K impressionnant avec un écran de 200+ inch. Pour soirées cinéma, football, gaming, mariages et événements d\'entreprise. Nous livrons, installons et démontons — vous profitez.',
      'hero.cta1': 'Vérifiez votre date <span aria-hidden="true">↗</span>',
      'hero.cta2': 'Contactez-nous sur WhatsApp',
      'hero.trust1': '<strong>4K</strong> image ultra nette',
      'hero.trust2': '<strong>200+ inch</strong> grand écran',
      'hero.trust3': '<strong>Clé en main</strong> livré & installé',
      'hero.trust4': '<strong>Sans TVA</strong> tout compris',
      'hero.scrollaria': 'Faire défiler vers les occasions',
      'hero.scroll': 'Découvrir',
      'marquee': '<span>Soirées cinéma</span><i>✦</i><span>Football & Coupe du Monde 2026</span><i>✦</i><span>Gaming & esports</span><i>✦</i><span>Mariages</span><i>✦</i><span>Événements d\'entreprise</span><i>✦</i><span>Communion & anniversaire</span><i>✦</i><span>Fêtes de fin d\'année</span><i>✦</i><span>Home cinéma</span><i>✦</i><span>Soirées cinéma</span><i>✦</i><span>Football & Coupe du Monde 2026</span><i>✦</i><span>Gaming & esports</span><i>✦</i><span>Mariages</span><i>✦</i><span>Événements d\'entreprise</span><i>✦</i><span>Communion & anniversaire</span><i>✦</i><span>Fêtes de fin d\'année</span><i>✦</i><span>Home cinéma</span><i>✦</i>',
      'occ.eyebrow': 'Pour chaque saison, chaque ambiance',
      'occ.title': 'Un écran.<br><em>Une infinité</em> de moments.',
      'occ.intro': 'D\'une douce soirée cinéma à une soirée Coupe du Monde endiablée : notre set premium transforme chaque rassemblement en une expérience dont on reparle longtemps. Toujours pour un usage privé ou un événement d\'entreprise interne.',
      'occ.tag': 'Coup de cœur',
      'occ.1.k': '01 — Douces soirées d\'été',
      'occ.1.t': 'Football & Coupe du Monde 2026',
      'occ.1.d': 'L\'ambiance du stade, tout simplement sur votre terrasse ou dans votre jardin.',
      'occ.2.k': '02 — Ready player one',
      'occ.2.t': 'Gaming & esports',
      'occ.2.d': 'Image 4K et faible input lag : jouez en grand sans compromis.',
      'occ.3.k': '03 — Un grand jour',
      'occ.3.t': 'Mariages & fêtes',
      'occ.3.d': 'Photos, vidéos et images d\'ambiance qui touchent vos invités.',
      'occ.4.k': '04 — Événement d\'entreprise interne',
      'occ.4.t': 'Présentations & galas',
      'occ.4.d': 'Town halls, lancements et remises de prix qui font la différence.',
      'occ.5.k': '05 — Supporter ensemble',
      'occ.5.t': 'Sport au jardin',
      'occ.5.d': 'Des amis, des boissons et le match sur grand écran sous les étoiles.',
      'occ.6.k': '06 — Privé au jardin',
      'occ.6.t': 'Cinéma de jardin & soirées cinéma',
      'occ.6.d': 'Un film, des plaids, des amis et un écran dont tout le monde se souvient.',
      'occ.foot': 'Aussi pour la <strong>communion & fête de la jeunesse laïque</strong>, les <strong>anniversaires</strong>, la <strong>Saint-Nicolas & fin d\'année</strong> et un <strong>home cinéma intérieur</strong>. <a href="#contact" class="text-link">Racontez-nous votre projet <span>→</span></a>',
      'usp.1.t': 'Une image vraiment grande',
      'usp.1.d': 'Un écran gonflable de 200+ inch et un projecteur laser 4K d\'environ 5.700 lumen. Lumineux, même au crépuscule.',
      'usp.2.t': 'Entièrement pris en charge',
      'usp.2.d': 'Livraison, installation, utilisation et reprise possibles. Vous n\'avez rien à porter ni à régler.',
      'usp.3.t': 'Local & personnel',
      'usp.3.d': 'Basés à Anvers. Des contacts directs, un service personnalisé et généralement une réponse sous un jour ouvrable.',
      'usp.4.t': 'Un prix clair',
      'usp.4.d': 'Exonéré de TVA. Ce que vous voyez, vous le payez — tout compris, sans surprise après coup.',
      'pkg.eyebrow': 'Tarifs transparents',
      'pkg.title': 'Choisissez votre niveau<br>de <em>tranquillité</em>.',
      'pkg.intro': 'Tous les prix sont des prix finaux. Beamerij est exonéré de TVA : aucune surprise, mais une formule complète.',
      'pkg.seo': 'Louer un projecteur à Anvers, louer un grand écran ou un écran de projection, ou louer directement projecteur et écran pour un cinéma en plein air privé : vous obtenez une seule solution premium. Louer un écran gonflable est aussi possible, en toute sérénité.',
      'pkg.from': 'à partir de',
      'pkg.night': '/ soirée',
      'pkg.featured': 'Le plus choisi',
      'pkg.avail': 'Vérifier la disponibilité <span>→</span>',
      'pkg.quote': 'Demandez votre devis <span>→</span>',
      'pkg.discuss': 'Parlons de votre événement <span>→</span>',
      'pkg.1.label': 'Compact',
      'pkg.1.t': 'Projecteur seul',
      'pkg.1.d': 'Pour qui dispose déjà d\'un écran ou d\'un mur blanc.',
      'pkg.1.sub': '€ 100 / week-end',
      'pkg.1.f1': 'Projecteur laser 4K',
      'pkg.1.f2': 'Câbles, télécommande & alimentation',
      'pkg.1.f3': 'Reprise sur rendez-vous',
      'pkg.2.label': 'Le set complet',
      'pkg.2.t': 'Full big-screen set',
      'pkg.2.d': 'Votre propre cinéma spectaculaire ou viewing party.',
      'pkg.2.sub': '€ 250 / week-end',
      'pkg.2.f1': 'Écran de projection gonflable 200+ inch + souffleur',
      'pkg.2.f2': 'Projecteur 4K, son & supports',
      'pkg.2.f3': 'Briefing clair pour l\'installation',
      'pkg.3.label': 'En toute sérénité',
      'pkg.3.t': 'Événement full-service',
      'pkg.3.d': 'De l\'arrivée au démontage : vous n\'avez rien à faire.',
      'pkg.3.sub': 'Anvers + 15 km',
      'pkg.3.f1': 'Tout de la formule B',
      'pkg.3.f2': 'Livraison, installation & reprise',
      'pkg.3.f3': 'Utilisation pendant votre événement',
      'pkg.4.label': 'Sur mesure',
      'pkg.4.t': 'Business & plusieurs jours',
      'pkg.4.d': 'Pour événements internes, location sur plusieurs jours ou besoins techniques supplémentaires.',
      'pkg.4.sub': 'prix sur demande',
      'pkg.4.f1': 'Concertation technique au préalable',
      'pkg.4.f2': 'Période de location flexible',
      'pkg.4.f3': 'Accompagnement supplémentaire possible',
      'pkg.note1': '<strong>Extras pratiques</strong><br>Livraison, installation & reprise € 50–80 · Opérateur sur place (formules A & B) € 100–125 · Enceinte ou câblage supplémentaire € 15–25',
      'pkg.note2': '<strong>Caution</strong><br>Projecteur € 300–400 · Full set € 500–750, ou carte d\'identité + convention signée.',
      'pkg.note3': '<strong>Tout compris, sans TVA</strong><br>Vous voyez immédiatement ce que vous payez. Aucune TVA n\'est facturée.',
      'proc.eyebrow': 'C\'est aussi simple que ça',
      'proc.title': 'De l\'idée à la<br><em>chair de poule.</em>',
      'proc.1.t': 'Demande',
      'proc.1.d': 'Dites-nous quand, où et pour quoi vous souhaitez utiliser l\'écran.',
      'proc.2.t': 'Confirmation',
      'proc.2.d': 'Vous recevez rapidement une proposition claire avec tous les arrangements pratiques.',
      'proc.3.t': 'Nous livrons & installons',
      'proc.3.d': 'En full-service, nous mettons tout en place de façon sûre et parfaite.',
      'proc.4.t': 'Vous profitez. Nous reprenons.',
      'proc.4.d': 'Après une soirée inoubliable, nous nous chargeons à nouveau du démontage.',
      'specs.eyebrow': 'Qu\'est-ce qui est inclus ?',
      'specs.title': 'Tout pour une<br><em>image</em> impressionnante.',
      'specs.intro': 'Pas de pièces de puzzle éparses. Notre set est soigneusement choisi pour créer un grand moment, à l\'intérieur comme à l\'extérieur.',
      'specs.caption': 'Un set premium. Entièrement harmonisé.',
      'specs.1': 'Écran de projection gonflable avec souffleur silencieux',
      'specs.2': 'Projecteur laser d\'environ 5.700 lumen, lumineux même au crépuscule',
      'specs.3.t': 'Audio',
      'specs.3': 'Set audio puissant avec tout le câblage nécessaire',
      'specs.4.t': 'Flexible',
      'specs.4': 'Pour jardin, terrasse, salle des fêtes, salon ou espace d\'entreprise',
      'specs.weather': '<strong>Bon à savoir :</strong> les installations extérieures dépendent de la météo. En cas de pluie ou de vent fort, nous cherchons ensemble et à temps une solution sûre.',
      'atmo.eyebrow': 'Grande image, grands souvenirs',
      'atmo.title': 'Certaines soirées<br><em>restent gravées.</em>',
      'atmo.copy': 'Une image nette de 200+ inch transforme une soirée ordinaire en quelque chose dont vos invités parleront encore des mois plus tard. Nous nous occupons de la technique. Vous, du moment.',
      'atmo.cta': 'Réservez votre soirée <span aria-hidden="true">↗</span>',
      'area.eyebrow': 'Local et proche',
      'area.title': 'Anvers<br><em>et alentours.</em>',
      'area.copy': 'Livraison et installation full-service à Anvers et dans un rayon d\'environ 15 km. Plus loin ? Demandez sans hésiter, nous verrons ce qui est possible.',
      'faq.eyebrow': 'À savoir d\'abord',
      'faq.title': 'Questions<br><em>fréquentes.</em>',
      'faq.intro': 'Votre question n\'y figure pas ? Envoyez-nous un message, et nous réfléchirons concrètement avec vous.',
      'faq.link': 'Contactez-nous <span>→</span>',
      'faq.1.q': 'Livrez-vous aussi ?',
      'faq.1.a': 'Oui. En full-service, nous livrons, installons et reprenons à Anvers et dans les communes environnantes. La livraison est aussi possible en option avec les autres formules.',
      'faq.2.q': 'Combien de temps dure l\'installation ?',
      'faq.2.a': 'Comptez généralement 30 à 60 minutes, selon le lieu et la configuration souhaitée. Nous planifions toujours cela bien avant le début de votre événement.',
      'faq.3.q': 'Que se passe-t-il s\'il pleut ou s\'il vente fort ?',
      'faq.3.a': 'La sécurité avant tout. En cas de météo défavorable, nous envisageons au préalable une alternative en intérieur, un nouveau moment ou une autre solution adaptée.',
      'faq.4.q': 'Comment fonctionne la caution ?',
      'faq.4.a': 'La caution s\'élève à € 300–400 pour le projecteur seul et à € 500–750 pour le full set. Dans certains cas, cela peut aussi se faire avec une carte d\'identité et une convention signée.',
      'faq.5.q': 'Que se passe-t-il en cas de dommage, perte ou vol ?',
      'faq.5.a': 'Le locataire est responsable du set depuis la réception jusqu\'à la reprise. Les dommages, pertes ou vols sont décomptés conformément aux conditions de location.',
      'faq.6.q': 'Puis-je annuler ?',
      'faq.6.a': 'C\'est possible selon les modalités de nos conditions générales. Comme nous réservons une date pour vous, des frais d\'annulation peuvent s\'appliquer lorsque l\'annulation intervient peu avant l\'événement.',
      'faq.7.q': 'Le set fonctionne-t-il en intérieur et en extérieur ?',
      'faq.7.a': 'Oui. Un jardin ou une terrasse, c\'est magnifique, mais nous réalisons aussi une projection impressionnante dans un salon, une salle des fêtes ou un espace de bureau. Nous adaptons l\'installation à votre espace.',
      'faq.8.q': 'De quoi avez-vous besoin en matière d\'électricité ?',
      'faq.8.a': 'Une prise normale et sûre à proximité suffit généralement. Faites-nous savoir au préalable si la distance est grande ou s\'il n\'y a pas d\'alimentation électrique sur place.',
      'contact.eyebrow': 'Votre date, votre moment',
      'contact.title': 'Rendez-le<br><em>inoubliable.</em>',
      'contact.copy': 'Demandez votre date sans engagement. Nous répondons rapidement avec la disponibilité et une proposition adaptée à votre projet.',
      'contact.phone': 'Appelez-nous',
      'contact.response': 'Généralement une réponse sous 1 jour ouvrable.',
      'contact.a1': 'Devis sans engagement & gratuit',
      'contact.a2': 'Conseil personnalisé sur mesure pour votre événement',
      'contact.a3': 'Sans TVA — tout compris',
      'form.name': 'Nom',
      'form.email': 'E-mail',
      'form.phone': 'Téléphone',
      'form.date': 'Date de l\'événement',
      'form.datehint': 'Pas encore sûr ? Indiquez volontiers une date indicative.',
      'form.location': 'Lieu / code postal',
      'form.package': 'Formule souhaitée',
      'form.choose': 'Choisissez une formule',
      'form.unsure': 'Je ne suis pas encore sûr',
      'form.message': 'Parlez-nous brièvement de votre événement',
      'form.placeholder': 'Par exemple : soirée cinéma pour 25 personnes, installation au jardin…',
      'form.consent': 'En envoyant, vous acceptez notre <a href="privacybeleid.html">politique de confidentialité</a>.',
      'form.submit': 'Demander un devis <span aria-hidden="true">↗</span>',
      'form.successtitle': 'Merci pour votre demande.',
      'form.successbody': 'Vous aurez généralement de nos nouvelles sous 1 jour ouvrable. Besoin rapide — par exemple pour un match de la Coupe du Monde ce week-end ? Envoyez-nous volontiers un <a href="https://wa.me/32XXXXXXXXX?text=Hoi%20Beamerij%2C%20ik%20heb%20net%20een%20aanvraag%20gedaan%20en%20het%20is%20wat%20dringend." target="_blank" rel="noopener noreferrer">WhatsApp</a>.',
      'form.sending': 'Envoi en cours…',
      'form.notconfigured': 'La connexion du formulaire n\'est pas encore configurée. En attendant, écrivez-nous à info@beamerij.be.',
      'form.error': 'L\'envoi a échoué. Réessayez ou écrivez-nous directement à info@beamerij.be.',
      'footer.tagline': 'Location big-screen premium pour des moments qui méritent de marquer.',
      'footer.cta': 'Demander un devis <span>↗</span>',
      'footer.nav': 'Navigation',
      'footer.call': 'Appelez-nous',
      'footer.book': 'Demander une date',
      'footer.region': 'Région',
      'footer.regionbody': 'Anvers + 15 km<br>Au-delà sur demande',
      'footer.vat': 'Petite entreprise soumise au régime de la franchise de la TVA - TVA non applicable.',
      'footer.privacy': 'Politique de confidentialité',
      'footer.cookies': 'Politique en matière de cookies',
      'footer.terms': 'Conditions générales',
      'footer.cookieprefs': 'Préférences de cookies',
      'footer.rights': 'Tous droits réservés.',
      'float.aria': 'Envoyez un message WhatsApp à Beamerij',
      'float.chat': 'Discutez avec nous',
      'totop.aria': 'Retour en haut'
    },
    en: {
      'meta.title': 'Beamerij | Rent a projector & big screen in Antwerp — 4K big-screen rental',
      'meta.desc': 'Beamerij rents premium 4K projectors, a 200+ inch projection screen and complete big-screen sets in Antwerp and surroundings. For movie nights, football, gaming, weddings and corporate events. Delivery and setup available.',
      'skip': 'Skip to content',
      'announce.aria': 'World Cup 2026 — book your matchday set',
      'announce.text': '<b>World Cup&nbsp;2026 is on</b> — watch every match on a 6&nbsp;metre screen. Book your matchday set.',
      'announce.cta': 'Check your date →',
      'nav.menu': 'Open menu',
      'nav.occasions': 'Occasions',
      'nav.packages': 'Packages',
      'nav.how': 'How it works',
      'nav.faq': 'FAQ',
      'nav.contact': 'Contact',
      'nav.cta': 'Request a quote <span aria-hidden="true">↗</span>',
      'hero.eyebrow': 'Premium projector rental in Antwerp',
      'hero.title': 'Big picture.<br><em>Every moment</em> special.',
      'hero.copy': 'One stunning 4K set with a 200+ inch screen. For movie nights, football, gaming, weddings and corporate events. We deliver, set up and clear away again — you just enjoy.',
      'hero.cta1': 'Check your date <span aria-hidden="true">↗</span>',
      'hero.cta2': 'WhatsApp us',
      'hero.trust1': '<strong>4K</strong> razor-sharp image',
      'hero.trust2': '<strong>200+ inch</strong> big screen',
      'hero.trust3': '<strong>Turnkey</strong> delivered & set up',
      'hero.trust4': '<strong>No VAT</strong> all-inclusive',
      'hero.scrollaria': 'Scroll to occasions',
      'hero.scroll': 'Discover',
      'marquee': '<span>Movie nights</span><i>✦</i><span>Football & World Cup 2026</span><i>✦</i><span>Gaming & esports</span><i>✦</i><span>Weddings</span><i>✦</i><span>Corporate events</span><i>✦</i><span>Communion & birthdays</span><i>✦</i><span>Year-end</span><i>✦</i><span>Home cinema</span><i>✦</i><span>Movie nights</span><i>✦</i><span>Football & World Cup 2026</span><i>✦</i><span>Gaming & esports</span><i>✦</i><span>Weddings</span><i>✦</i><span>Corporate events</span><i>✦</i><span>Communion & birthdays</span><i>✦</i><span>Year-end</span><i>✦</i><span>Home cinema</span><i>✦</i>',
      'occ.eyebrow': 'For every season, every setting',
      'occ.title': 'One screen.<br><em>Endless</em> moments.',
      'occ.intro': 'From a balmy movie night to a wild World Cup evening: our premium set turns any gathering into an experience worth talking about. Always for private use or an internal corporate event.',
      'occ.tag': 'Top pick',
      'occ.1.k': '01 — Balmy summer evenings',
      'occ.1.t': 'Football & World Cup 2026',
      'occ.1.d': 'The stadium feeling, right on your own terrace or in the garden.',
      'occ.2.k': '02 — Ready player one',
      'occ.2.t': 'Gaming & esports',
      'occ.2.d': '4K image and low input lag: play big without compromise.',
      'occ.3.k': '03 — A big day',
      'occ.3.t': 'Weddings & celebrations',
      'occ.3.d': 'Photos, video and mood visuals that move your guests.',
      'occ.4.k': '04 — Internal corporate event',
      'occ.4.t': 'Presentations & galas',
      'occ.4.d': 'Town halls, launches and awards with a visible difference.',
      'occ.5.k': '05 — Cheering together',
      'occ.5.t': 'Sport in the garden',
      'occ.5.d': 'Friends, drinks and the match on a big screen under the stars.',
      'occ.6.k': '06 — Private in the garden',
      'occ.6.t': 'Garden cinema & movie nights',
      'occ.6.d': 'A film, blankets, friends and a screen everyone will remember.',
      'occ.foot': 'Also for <strong>communion & spring celebrations</strong>, <strong>birthdays</strong>, <strong>Sinterklaas & year-end</strong> and an <strong>indoor home cinema</strong>. <a href="#contact" class="text-link">Tell us your plan <span>→</span></a>',
      'usp.1.t': 'Truly big picture',
      'usp.1.d': 'A 200+ inch inflatable screen and a 4K laser projector of around 5.700 lumen. Bright, even at dusk.',
      'usp.2.t': 'Fully taken care of',
      'usp.2.d': 'Delivery, setup, operation and pickup available. You never have to haul or configure a thing.',
      'usp.3.t': 'Local & personal',
      'usp.3.d': 'Based in Antwerp. Short lines, personal contact and usually a reply within one working day.',
      'usp.4.t': 'One clear price',
      'usp.4.d': 'Exempt from VAT. What you see is what you pay — all-inclusive, no surprises afterwards.',
      'pkg.eyebrow': 'Clearly priced',
      'pkg.title': 'Choose how much<br><em>peace of mind</em> you want.',
      'pkg.intro': 'All prices are final prices. Beamerij is exempt from VAT: no surprises, just a complete package.',
      'pkg.seo': 'Whether you rent a projector in Antwerp, rent a big screen or projection screen, or rent projector and screen together for a private outdoor cinema: you get one premium solution. Renting an inflatable screen can be completely worry-free too.',
      'pkg.from': 'from',
      'pkg.night': '/ night',
      'pkg.featured': 'Most chosen',
      'pkg.avail': 'Ask about availability <span>→</span>',
      'pkg.quote': 'Request your quote <span>→</span>',
      'pkg.discuss': 'Discuss your event <span>→</span>',
      'pkg.1.label': 'Compact',
      'pkg.1.t': 'Projector only',
      'pkg.1.d': 'For those who already have a screen or white wall.',
      'pkg.1.sub': '€ 100 / weekend',
      'pkg.1.f1': '4K laser projector',
      'pkg.1.f2': 'Cables, remote control & power',
      'pkg.1.f3': 'Pickup by appointment',
      'pkg.2.label': 'The complete set',
      'pkg.2.t': 'Full big-screen set',
      'pkg.2.d': 'Your own spectacular cinema or viewing party.',
      'pkg.2.sub': '€ 250 / weekend',
      'pkg.2.f1': '200+ inch inflatable projection screen + blower',
      'pkg.2.f2': '4K projector, sound & stands',
      'pkg.2.f3': 'Clear self-setup briefing',
      'pkg.3.label': 'Completely worry-free',
      'pkg.3.t': 'Full-service event',
      'pkg.3.d': 'From arrival to teardown: you don\'t have to do a thing.',
      'pkg.3.sub': 'Antwerp + 15 km',
      'pkg.3.f1': 'Everything from package B',
      'pkg.3.f2': 'Delivery, setup & pickup',
      'pkg.3.f3': 'Operation during your event',
      'pkg.4.label': 'Tailor-made',
      'pkg.4.t': 'Business & multi-day',
      'pkg.4.d': 'For internal events, multi-day rental or extra technical needs.',
      'pkg.4.sub': 'price on request',
      'pkg.4.f1': 'Technical alignment beforehand',
      'pkg.4.f2': 'Flexible rental period',
      'pkg.4.f3': 'Extra support available',
      'pkg.note1': '<strong>Handy extras</strong><br>Delivery, setup & pickup € 50–80 · On-site operator (package A & B) € 100–125 · Extra speaker or cabling € 15–25',
      'pkg.note2': '<strong>Deposit</strong><br>Projector € 300–400 · Full set € 500–750, or ID card + signed agreement.',
      'pkg.note3': '<strong>All-inclusive, no VAT</strong><br>You see straight away what you pay. No VAT is charged.',
      'proc.eyebrow': 'It\'s this simple',
      'proc.title': 'From idea to<br><em>goosebumps.</em>',
      'proc.1.t': 'Request',
      'proc.1.d': 'Tell us when, where and what you want to use the screen for.',
      'proc.2.t': 'Confirmation',
      'proc.2.d': 'You quickly get a clear proposal with all the practical arrangements.',
      'proc.3.t': 'We deliver & install',
      'proc.3.d': 'With full-service we set everything up safely and perfectly in place.',
      'proc.4.t': 'You enjoy. We pick up.',
      'proc.4.d': 'After an unforgettable evening we take the teardown off your hands again.',
      'specs.eyebrow': 'What\'s included?',
      'specs.title': 'Everything for an<br><em>impressive</em> picture.',
      'specs.intro': 'No loose puzzle pieces. Our set is carefully chosen to create a grand moment both indoors and out.',
      'specs.caption': 'One premium set. Fully dialled in.',
      'specs.1': 'Inflatable projection screen with quiet blower',
      'specs.2': 'Laser projector of around 5.700 lumen, bright even at dusk',
      'specs.3.t': 'Audio',
      'specs.3': 'Powerful sound set with all the cabling you need',
      'specs.4.t': 'Flexible',
      'specs.4': 'For garden, terrace, function room, living room or business space',
      'specs.weather': '<strong>Good to know:</strong> outdoor setups depend on the weather. In case of rain or strong wind, we look for a safe solution together in good time.',
      'atmo.eyebrow': 'Big picture, big memories',
      'atmo.title': 'Some evenings<br><em>just stick with you.</em>',
      'atmo.copy': 'A sharp 200+ inch image turns an ordinary evening into something your guests will talk about for months. We handle the tech. You handle the moment.',
      'atmo.cta': 'Book your evening <span aria-hidden="true">↗</span>',
      'area.eyebrow': 'Local and close by',
      'area.title': 'Antwerp<br><em>and surroundings.</em>',
      'area.copy': 'Full-service delivery and setup in Antwerp and within about 15 km. Further away? Feel free to ask and we\'ll see what\'s possible.',
      'faq.eyebrow': 'First, the essentials',
      'faq.title': 'Frequently asked<br><em>questions.</em>',
      'faq.intro': 'Don\'t see your question? Send us a message and we\'ll think it through with you, concretely.',
      'faq.link': 'Get in touch <span>→</span>',
      'faq.1.q': 'Do you deliver too?',
      'faq.1.a': 'Yes. With full-service we deliver, set up and pick up in Antwerp and the surrounding municipalities. Delivery is also available as an extra with the other packages.',
      'faq.2.q': 'How long does setup take?',
      'faq.2.a': 'Generally count on 30 to 60 minutes, depending on the location and the setup you want. We always plan this well ahead of the start of your event.',
      'faq.3.q': 'What if it rains or the wind picks up?',
      'faq.3.a': 'Safety comes first. In unsuitable weather we look in advance at an indoor alternative, a new date or another fitting solution.',
      'faq.4.q': 'How does the deposit work?',
      'faq.4.a': 'The deposit is € 300–400 for the projector only and € 500–750 for the full set. In some cases this can also be done with an ID card and a signed agreement.',
      'faq.5.q': 'What about damage, loss or theft?',
      'faq.5.a': 'The renter is responsible for the set from receipt until pickup. Damage, loss or theft is settled according to the rental terms.',
      'faq.6.q': 'Can I cancel?',
      'faq.6.a': 'You can, in line with the terms in our general conditions. Because we reserve a date for you, cancellation fees may apply when the cancellation happens close to the event.',
      'faq.7.q': 'Can the set be used indoors and outdoors?',
      'faq.7.a': 'Yes. A garden or terrace is lovely, but we create an impressive projection in a living room, function room or office space too. We tailor the setup to your space.',
      'faq.8.q': 'What do you need in terms of power?',
      'faq.8.a': 'A normal, safe socket nearby is usually enough. Let us know in advance if the distance is large or if there\'s no power supply at the location.',
      'contact.eyebrow': 'Your date, your moment',
      'contact.title': 'Make it<br><em>unforgettable.</em>',
      'contact.copy': 'Request your date with no obligation. We\'ll reply quickly with availability and a proposal that fits your plan.',
      'contact.phone': 'Give us a call',
      'contact.response': 'Usually a reply within 1 working day.',
      'contact.a1': 'No-obligation & free quote',
      'contact.a2': 'Personal advice tailored to your event',
      'contact.a3': 'No VAT — all-inclusive',
      'form.name': 'Name',
      'form.email': 'Email',
      'form.phone': 'Phone',
      'form.date': 'Event date',
      'form.datehint': 'Not sure yet? Feel free to give a rough date.',
      'form.location': 'Location / postcode',
      'form.package': 'Preferred package',
      'form.choose': 'Choose a package',
      'form.unsure': 'I\'m not sure yet',
      'form.message': 'Tell us a little about your event',
      'form.placeholder': 'For example: movie night for 25 people, setup in the garden…',
      'form.consent': 'By submitting you agree to our <a href="privacybeleid.html">privacy policy</a>.',
      'form.submit': 'Request a quote <span aria-hidden="true">↗</span>',
      'form.successtitle': 'Thanks for your request.',
      'form.successbody': 'You\'ll usually hear from us within 1 working day. Need it fast — for a World Cup match this weekend, say? Feel free to send us a <a href="https://wa.me/32XXXXXXXXX?text=Hoi%20Beamerij%2C%20ik%20heb%20net%20een%20aanvraag%20gedaan%20en%20het%20is%20wat%20dringend." target="_blank" rel="noopener noreferrer">WhatsApp</a>.',
      'form.sending': 'Just sending…',
      'form.notconfigured': 'The form connection isn\'t set up yet. In the meantime, email us at info@beamerij.be.',
      'form.error': 'Sending didn\'t work. Please try again or email us directly at info@beamerij.be.',
      'footer.tagline': 'Premium big-screen rental for moments that deserve to land.',
      'footer.cta': 'Request a quote <span>↗</span>',
      'footer.nav': 'Navigation',
      'footer.call': 'Call us',
      'footer.book': 'Request a date',
      'footer.region': 'Region',
      'footer.regionbody': 'Antwerp + 15 km<br>Beyond that on request',
      'footer.vat': 'Small business subject to the VAT exemption scheme - VAT not applicable.',
      'footer.privacy': 'Privacy policy',
      'footer.cookies': 'Cookie policy',
      'footer.terms': 'General conditions',
      'footer.cookieprefs': 'Cookie preferences',
      'footer.rights': 'All rights reserved.',
      'float.aria': 'Send Beamerij a WhatsApp message',
      'float.chat': 'Chat with us',
      'totop.aria': 'Back to top'
    }
  };

  function getInitial() {
    try { var s = localStorage.getItem(STORE); if (s && SUPPORTED.indexOf(s) > -1) return s; } catch (e) {}
    try { var u = new URLSearchParams(location.search).get('lang'); if (u && SUPPORTED.indexOf(u) > -1) return u; } catch (e) {}
    var b = (navigator.language || 'nl').slice(0, 2).toLowerCase();
    return SUPPORTED.indexOf(b) > -1 ? b : 'nl';
  }

  var current = 'nl';
  function val(key) { var d = DICT[current] || {}; return d[key] != null ? d[key] : DICT.nl[key]; }

  function apply(lang) {
    current = SUPPORTED.indexOf(lang) > -1 ? lang : 'nl';
    document.querySelectorAll('[data-i18n]').forEach(function (el) { var v = val(el.getAttribute('data-i18n')); if (v != null) el.innerHTML = v; });
    document.querySelectorAll('[data-i18n-ph]').forEach(function (el) { var v = val(el.getAttribute('data-i18n-ph')); if (v != null) el.setAttribute('placeholder', v); });
    document.querySelectorAll('[data-i18n-al]').forEach(function (el) { var v = val(el.getAttribute('data-i18n-al')); if (v != null) el.setAttribute('aria-label', v); });
    if (val('meta.title')) document.title = val('meta.title');
    var md = document.querySelector('meta[name="description"]'); if (md && val('meta.desc')) md.setAttribute('content', val('meta.desc'));
    document.documentElement.setAttribute('lang', current === 'nl' ? 'nl-BE' : current);
    document.querySelectorAll('[data-lang]').forEach(function (b) { b.setAttribute('aria-pressed', String(b.getAttribute('data-lang') === current)); });
    window.__lang = current;
  }
  window.t = function (key) { return val(key) || ''; };

  var reduced = false;
  try { reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches; } catch (e) {}

  function set(lang) {
    if (SUPPORTED.indexOf(lang) < 0) return;
    try { localStorage.setItem(STORE, lang); } catch (e) {}
    if (reduced || lang === current) { apply(lang); return; }
    document.body.classList.add('lang-switching');           // fade + blur current text out
    window.setTimeout(function () {
      apply(lang);                                           // swap text while hidden
      window.requestAnimationFrame(function () {             // next frame: fade back in
        document.body.classList.remove('lang-switching');
      });
    }, 240);
  }
  window.__setLang = set;
  document.addEventListener('click', function (e) {
    var b = e.target.closest && e.target.closest('[data-lang]');
    if (!b) return;
    e.preventDefault();
    set(b.getAttribute('data-lang'));
  });

  apply(getInitial());
})();
