/* ============================================================
   Beamerij — language switcher (NL / FR / EN)
   Client-side i18n. Dutch is the source; FR and EN are below.
   Choice is saved in localStorage; ?lang=fr|en and browser
   language are honoured on first visit.
   ============================================================ */
(function () {
  var SUPPORTED = ['nl', 'fr', 'en'];
  var STORE = 'beamerij-lang';

  var DICT = {
    nl: {
      'meta.title': 'Beamerij | Beamer & groot scherm huren in Antwerpen — 4K big-screen verhuur',
      'meta.desc': 'Beamerij verhuurt premium 4K beamers, een 200+ inch projectiescherm en complete big-screen sets in Antwerpen e.o. Voor filmavonden, voetbal, gaming, huwelijken en bedrijfsevents. Levering en opbouw mogelijk.',
      'skip': 'Ga naar inhoud',
      'announce.aria': 'WK 2026 — check je datum',
      'announce.text': '<b>WK&nbsp;2026 is bezig</b> — elke match op een scherm van 6&nbsp;meter, gewoon in je tuin.',
      'announce.cta': 'Check je datum →',
      'nav.menu': 'Menu openen',
      'nav.packages': 'Pakketten &amp; prijzen',
      'nav.set': 'De set',
      'nav.occasions': 'Gelegenheden',
      'nav.how': 'Zo werkt het',
      'nav.faq': 'FAQ',
      'nav.contact': 'Contact',
      'nav.callaria': 'Bel Beamerij',
      'nav.cta': 'Offerte aanvragen',
      'hero.title': 'Beamer en groot scherm huren in Antwerpen',
      'hero.copy': 'Een complete 4K-set: opblaasbaar scherm van 200+ inch, laserprojector en geluid. Zelf afhalen of volledig geleverd en opgebouwd — voor je filmavond, de match, een feest of een bedrijfsevent.',
      'hero.price': 'Beamer vanaf <strong>€ 70</strong>, complete set vanaf <strong>€ 175</strong> per avond. Alles inbegrepen, geen btw.',
      'hero.trust1': 'Opblaasbaar scherm van 200+ inch',
      'hero.trust2': '4K laserprojector van 5.700 lumen',
      'hero.trust3': 'Geluidsset en alle kabels inbegrepen',
      'hero.trust4': 'Levering en opbouw mogelijk',
      'quick.label': 'Datum van je event',
      'quick.cta': 'Check beschikbaarheid',
      'quick.note': 'Vrijblijvend en gratis · meestal antwoord binnen 1 werkdag',
      'quick.wa': 'of stuur een WhatsApp',
      'strip.1.t': 'Eén eindprijs',
      'strip.1.d': 'Vrijgesteld van btw, alles inbegrepen. De prijs die je ziet, is wat je betaalt.',
      'strip.2.t': 'Levering &amp; opbouw',
      'strip.2.d': 'Wij leveren en bouwen op in Antwerpen en omstreken. Zelf afhalen kan ook.',
      'strip.3.t': 'Werkt overal',
      'strip.3.d': 'Binnen of buiten, met of zonder stopcontact — stille powerstation als optie.',
      'strip.4.t': 'Snel antwoord',
      'strip.4.d': 'Meestal hoor je binnen één werkdag of je datum nog vrij is.',
      'pkg.title': 'Pakketten en prijzen',
      'pkg.intro': 'Alle prijzen zijn eindprijzen, vrijgesteld van btw. Huur alleen de beamer of laat alles voor je regelen.',
      'pkg.from': 'vanaf', 'pkg.night': '/ avond', 'pkg.featured': 'Meest gekozen',
      'pkg.avail': 'Check beschikbaarheid', 'pkg.quote': 'Vraag je offerte', 'pkg.discuss': 'Bespreek je event',
      'pkg.1.t': 'Alleen beamer', 'pkg.1.d': 'Voor wie zelf een scherm of witte muur heeft.', 'pkg.1.sub': '€ 100 voor een heel weekend', 'pkg.1.f1': '4K laserprojector', 'pkg.1.f2': 'Kabels en afstandsbediening', 'pkg.1.f3': 'Afhalen en terugbrengen op afspraak',
      'pkg.2.t': 'Full big-screen set', 'pkg.2.d': 'Scherm, beeld en geluid — jouw eigen openluchtcinema.', 'pkg.2.sub': '€ 250 voor een heel weekend', 'pkg.2.f1': 'Opblaasbaar scherm van 200+ inch met stille blower', 'pkg.2.f2': '4K laserprojector, geluidsset en stands', 'pkg.2.f3': 'Duidelijke uitleg voor het opzetten',
      'pkg.3.t': 'Full-service event', 'pkg.3.d': 'Wij leveren, bouwen op en halen weer op. Jij doet niets.', 'pkg.3.sub': 'Antwerpen + 15 km', 'pkg.3.f1': 'Alles uit de full set', 'pkg.3.f2': 'Levering, opbouw en ophaling inbegrepen', 'pkg.3.f3': 'Bediening tijdens je event', 'pkg.3.f4': 'Geen waarborg nodig',
      'pkg.4.t': 'Business &amp; meerdaags', 'pkg.4.d': 'Voor interne bedrijfsevents en huur van meerdere dagen.', 'pkg.4.sub': 'prijs op maat', 'pkg.4.f1': 'Technische afstemming vooraf', 'pkg.4.f2': 'Flexibele huurperiode', 'pkg.4.f3': 'Begeleiding tijdens het event mogelijk',
      'pkg.note1': "<strong>Extra's</strong> — Levering, opbouw &amp; ophaling € 50–80 · Operator ter plaatse (pakket A &amp; B) € 100–125 · Extra speaker of bekabeling € 15–25",
      'pkg.note2': '<strong>Waarborg</strong> — Beamer € 300–400 · Full set € 500–750, of met identiteitskaart en ondertekende overeenkomst · Full-service: <strong>geen waarborg</strong>.',
      'pkg.note3': '<strong>Geen btw</strong> — Beamerij is vrijgesteld van btw. De prijs die je ziet, is de prijs die je betaalt.',
      'addon.title': 'Handige opties', 'addon.onrequest': 'Op aanvraag',
      'addon.1.t': 'Gaming-set (PS5)', 'addon.1.d': 'PlayStation 5 met twee draadloze controllers. FIFA of Mario Kart op 200+ inch.',
      'addon.2.t': 'Fotograaf &amp; videograaf', 'addon.2.d': "Een professional legt je event vast — sfeerbeelden, groepsfoto's of een aftermovie.",
      'addon.3.t': 'Stroom zonder stopcontact', 'addon.3.d': 'Stille, krachtige powerstation (accu) zodat de set overal kan draaien.',
      'set.title': 'Dit zit er in de set',
      'set.intro': 'Geen losse onderdelen bij elkaar zoeken: alles is op elkaar afgestemd en werkt binnen én buiten.',
      'set.i1': 'Opblaasbaar projectiescherm van 200+ inch met stille blower',
      'set.i2': '4K laserprojector van 5.700 lumen — helder, ook bij schemering',
      'set.i3': 'Krachtige geluidsset met alle nodige bekabeling',
      'set.i4': 'Stands, kabels en afstandsbediening',
      'set.i5': 'Geschikt voor tuin, terras, living, feestzaal of kantoor',
      'set.weather': '<strong>Goed om te weten:</strong> buitenopstellingen zijn weersafhankelijk. Bij regen of felle wind zoeken we samen op tijd een veilige oplossing. Zorg ook dat de plek donker genoeg is — hoe minder licht, hoe mooier het beeld.',
      'occ.title': 'Voor de match, een filmavond, gaming of een feest',
      'occ.intro': 'Voor privégebruik en interne bedrijfsevents, binnen of buiten. Dit zijn de populairste gelegenheden.',
      'occ.tag': 'WK 2026 · nu bezig',
      'occ.1.t': 'Voetbal &amp; WK 2026', 'occ.1.d': 'De match op groot scherm op je terras of in je tuin.',
      'occ.2.t': 'Tuincinema &amp; filmavond', 'occ.2.d': 'Openluchtcinema voor familie, vrienden of de hele straat.',
      'occ.3.t': 'Gaming &amp; esports', 'occ.3.d': 'FIFA, Mario Kart of races op 200+ inch — PS5 bij te huren.',
      'occ.4.t': 'Huwelijken &amp; feesten', 'occ.4.d': "Foto's, video's en sfeerbeelden voor jullie gasten.",
      'occ.5.t': 'Bedrijfsevents', 'occ.5.d': 'Presentaties, town halls en personeelsfeesten, intern bij jullie.',
      'occ.6.t': 'Sport in de tuin', 'occ.6.d': 'Champions League, de Ronde of de Tour — samen supporteren.',
      'occ.foot': 'Ook voor communie of lentefeest, verjaardagen, eindejaar of een home cinema in de living. <a href="#contact" class="text-link">Vertel ons je plan</a>',
      'proc.title': 'Zo werkt het',
      'proc.1.t': 'Vraag je datum aan', 'proc.1.d': 'Via het formulier, WhatsApp of telefoon. Je hoort snel of je datum vrij is.',
      'proc.2.t': 'Ontvang je voorstel', 'proc.2.d': 'Eén duidelijke totaalprijs met alle praktische afspraken op een rij.',
      'proc.3.t': 'Wij leveren en bouwen op', 'proc.3.d': "Of je haalt de set zelf af. De opbouw duurt zo'n 30 tot 60 minuten.",
      'proc.4.t': 'Jij geniet, wij ruimen op', 'proc.4.d': 'Na je event halen we alles weer op, of breng je de set gewoon terug.',
      'proc.cta': 'Vraag je datum aan',
      'wk.kicker': 'WK 2026 · nog tot 19 juli',
      'wk.title': 'De volgende match op een scherm van 200+ inch',
      'wk.copy': 'Kwartfinales, halve finales, dé finale: haal het stadiongevoel naar je tuin of terras. Weekenddata gaan het snelst — check die van jou op tijd.',
      'wk.cta': 'Reserveer je matchday',
      'area.title': 'Levering in Antwerpen en omstreken',
      'area.copy': 'Full-service levering en opbouw in Antwerpen en tot ongeveer 15 km errond. Zelf afhalen kan altijd. Ligt je locatie verder? Stuur een berichtje, dan bekijken we wat mogelijk is.',
      'faq.title': 'Veelgestelde vragen',
      'faq.intro': 'Staat je vraag er niet tussen? Stuur ons een berichtje.',
      'faq.link': 'Stel je vraag',
      'faq.1.q': 'Leveren jullie ook?', 'faq.1.a': 'Ja. Bij full-service leveren, bouwen en halen we op in Antwerpen en de omliggende gemeenten. De levering is ook als extra bij andere pakketten mogelijk.',
      'faq.2.q': 'Hoe lang duurt de opbouw?', 'faq.2.a': 'Reken doorgaans op 30 tot 60 minuten, afhankelijk van de locatie en de gewenste opstelling. We plannen dit altijd ruim voor de start van je event.',
      'faq.3.q': 'Wat als het regent of hard waait?', 'faq.3.a': 'Veiligheid komt eerst. Bij ongeschikt weer bekijken we vooraf een binnenalternatief, een nieuw moment of een andere passende oplossing.',
      'faq.4.q': 'Hoe werkt de waarborg?', 'faq.4.a': 'De waarborg bedraagt € 300–400 voor alleen de beamer en € 500–750 voor de full set. In sommige gevallen kan dit ook met een identiteitskaart en ondertekende overeenkomst. Kies je voor het full-service pakket, met levering én bediening ter plaatse? Dan betaal je geen waarborg.',
      'faq.5.q': 'Wat bij schade, verlies of diefstal?', 'faq.5.a': 'De huurder is verantwoordelijk voor de set vanaf ontvangst tot ophaling. Schade, verlies of diefstal wordt volgens de huurvoorwaarden verrekend.',
      'faq.6.q': 'Kan ik annuleren?', 'faq.6.a': 'Dat kan volgens de afspraken in onze algemene voorwaarden. Omdat we een datum voor je reserveren, kunnen annuleringskosten gelden wanneer de annulering dicht bij het event gebeurt.',
      'faq.7.q': 'Kan de set binnen én buiten?', 'faq.7.a': 'Ja. Een tuin of terras is mooi, maar ook in een living, feestzaal of kantoorruimte maken we een indrukwekkende projectie. We stemmen de opstelling af op je ruimte.',
      'faq.8.q': 'Wat hebben jullie nodig qua stroom?', 'faq.8.a': 'Een normaal, veilig stopcontact in de buurt is meestal voldoende. Laat vooraf weten als de afstand groot is of als er geen stroomvoorziening op de locatie is — dan brengen we een stille powerstation (accu) mee zodat je show toch kan doorgaan.',
      'contact.title': 'Check je datum',
      'contact.copy': 'Vul het formulier in en je weet snel of je datum nog vrij is — met meteen een concreet voorstel erbij. Bellen of WhatsAppen kan ook.',
      'contact.phone': 'Bel <b>0485&nbsp;06&nbsp;69&nbsp;91</b>',
      'contact.response': 'Meestal antwoord binnen 1 werkdag.',
      'contact.a1': 'Vrijblijvend en gratis', 'contact.a2': 'Eindprijs zonder btw — geen verrassingen', 'contact.a3': 'Advies op maat van jouw locatie',
      'form.name': 'Naam', 'form.email': 'E-mail', 'form.phone': 'Telefoon', 'form.date': 'Datum event',
      'form.datehint': 'Nog niet zeker? Geef gerust een richtdatum.',
      'form.location': 'Locatie / postcode', 'form.package': 'Gewenst pakket', 'form.choose': 'Kies een pakket', 'form.unsure': 'Ik ben nog niet zeker',
      'form.message': 'Vertel kort iets over je event', 'form.placeholder': 'Bijvoorbeeld: filmavond voor 25 personen, opbouw in de tuin…',
      'form.consent': 'Door te versturen ga je akkoord met ons <a href="privacybeleid.html">privacybeleid</a>.',
      'form.submit': 'Vraag vrijblijvend je offerte',
      'form.successtitle': 'Bedankt voor je aanvraag.',
      'form.successbody': 'Je hoort meestal binnen 1 werkdag van ons. Snel nodig — bijvoorbeeld voor een WK-match dit weekend? Stuur ons gerust een <a href="https://wa.me/32485066991?text=Hoi%20Beamerij%2C%20ik%20heb%20net%20een%20aanvraag%20gedaan%20en%20het%20is%20wat%20dringend." target="_blank" rel="noopener noreferrer">WhatsApp</a>.',
      'form.sending': 'Even versturen…',
      'form.notconfigured': 'De formulierkoppeling is nog niet ingesteld. Mail ons intussen via info@beamerij.be.',
      'form.error': 'Versturen lukte niet. Probeer opnieuw of mail ons rechtstreeks via info@beamerij.be.',
      'footer.tagline': 'Beamer- en big-screenverhuur voor privé-events en interne bedrijfsevents, vanuit Antwerpen.',
      'footer.cta': 'Offerte aanvragen',
      'footer.nav': 'Navigatie', 'footer.book': 'Datum aanvragen',
      'footer.region': 'Regio', 'footer.regionbody': 'Antwerpen + 15 km<br>Daarbuiten op aanvraag',
      'footer.vat': 'Kleine onderneming onderworpen aan de vrijstellingsregeling van btw - btw niet van toepassing.',
      'footer.privacy': 'Privacybeleid', 'footer.cookies': 'Cookiebeleid', 'footer.terms': 'Algemene voorwaarden', 'footer.cookieprefs': 'Cookievoorkeuren',
      'footer.rights': 'Alle rechten voorbehouden.',
      'float.aria': 'Stuur Beamerij een WhatsAppbericht', 'float.chat': 'Chat met ons',
      'totop.aria': 'Terug naar boven'
    },
    fr: {
      'meta.title': 'Beamerij | Location de projecteur & grand écran à Anvers — location big-screen 4K',
      'meta.desc': 'Beamerij loue des projecteurs 4K premium, un écran de projection 200+ inch et des sets big-screen complets à Anvers et alentours. Pour soirées cinéma, football, gaming, mariages et événements d\'entreprise. Livraison et installation possibles.',
      'skip': 'Aller au contenu',
      'announce.aria': 'Coupe du Monde 2026 — vérifiez votre date',
      'announce.text': '<b>La Coupe du Monde&nbsp;2026 bat son plein</b> — chaque match sur un écran de 6&nbsp;mètres, dans votre jardin.',
      'announce.cta': 'Vérifiez votre date →',
      'nav.menu': 'Ouvrir le menu',
      'nav.packages': 'Formules &amp; prix',
      'nav.set': 'Le set',
      'nav.occasions': 'Occasions',
      'nav.how': 'Comment ça marche',
      'nav.faq': 'FAQ',
      'nav.contact': 'Contact',
      'nav.callaria': 'Appeler Beamerij',
      'nav.cta': 'Demander un devis',
      'hero.title': 'Louez un projecteur et un grand écran à Anvers',
      'hero.copy': 'Un set 4K complet : écran gonflable de 200+ inch, projecteur laser et son. À retirer vous-même ou livré et installé — pour une soirée cinéma, le match, une fête ou un événement d\'entreprise.',
      'hero.price': 'Projecteur seul à partir de <strong>€ 70</strong>, set complet à partir de <strong>€ 175</strong> par soirée. Tout compris, sans TVA.',
      'hero.trust1': 'Écran gonflable de 200+ inch',
      'hero.trust2': 'Projecteur laser 4K de 5.700 lumens',
      'hero.trust3': 'Set audio et tous les câbles inclus',
      'hero.trust4': 'Livraison et installation possibles',
      'quick.label': 'Date de votre événement',
      'quick.cta': 'Vérifier la disponibilité',
      'quick.note': 'Gratuit et sans engagement · réponse généralement sous 1 jour ouvrable',
      'quick.wa': 'ou envoyez un WhatsApp',
      'strip.1.t': 'Un prix final',
      'strip.1.d': 'Exonéré de TVA, tout compris. Le prix affiché est celui que vous payez.',
      'strip.2.t': 'Livraison &amp; installation',
      'strip.2.d': 'Nous livrons et installons à Anvers et alentours. Le retrait est aussi possible.',
      'strip.3.t': 'Fonctionne partout',
      'strip.3.d': 'À l\'intérieur ou dehors, avec ou sans prise — batterie silencieuse en option.',
      'strip.4.t': 'Réponse rapide',
      'strip.4.d': 'Vous savez généralement sous un jour ouvrable si votre date est libre.',
      'pkg.title': 'Formules et prix',
      'pkg.intro': 'Tous les prix sont des prix finaux, exonérés de TVA. Louez uniquement le projecteur ou laissez-nous tout organiser.',
      'pkg.from': 'à partir de', 'pkg.night': '/ soirée', 'pkg.featured': 'Le plus choisi',
      'pkg.avail': 'Vérifier la disponibilité', 'pkg.quote': 'Demandez votre devis', 'pkg.discuss': 'Parlons de votre événement',
      'pkg.1.t': 'Projecteur seul', 'pkg.1.d': 'Si vous avez déjà un écran ou un mur blanc.', 'pkg.1.sub': '€ 100 pour tout le week-end', 'pkg.1.f1': 'Projecteur laser 4K', 'pkg.1.f2': 'Câbles et télécommande', 'pkg.1.f3': 'Retrait et retour sur rendez-vous',
      'pkg.2.t': 'Full big-screen set', 'pkg.2.d': 'Écran, image et son — votre cinéma en plein air.', 'pkg.2.sub': '€ 250 pour tout le week-end', 'pkg.2.f1': 'Écran gonflable de 200+ inch avec souffleur silencieux', 'pkg.2.f2': 'Projecteur laser 4K, set audio et supports', 'pkg.2.f3': 'Explications claires pour l\'installation',
      'pkg.3.t': 'Événement full-service', 'pkg.3.d': 'Nous livrons, installons et reprenons. Vous ne faites rien.', 'pkg.3.sub': 'Anvers + 15 km', 'pkg.3.f1': 'Tout du set complet', 'pkg.3.f2': 'Livraison, installation et reprise incluses', 'pkg.3.f3': 'Utilisation pendant votre événement', 'pkg.3.f4': 'Aucune caution demandée',
      'pkg.4.t': 'Business &amp; plusieurs jours', 'pkg.4.d': 'Pour événements internes d\'entreprise et locations de plusieurs jours.', 'pkg.4.sub': 'prix sur mesure', 'pkg.4.f1': 'Concertation technique au préalable', 'pkg.4.f2': 'Période de location flexible', 'pkg.4.f3': 'Accompagnement possible pendant l\'événement',
      'pkg.note1': '<strong>Extras</strong> — Livraison, installation &amp; reprise € 50–80 · Opérateur sur place (formules A &amp; B) € 100–125 · Enceinte ou câblage en plus € 15–25',
      'pkg.note2': '<strong>Caution</strong> — Projecteur € 300–400 · Full set € 500–750, ou carte d\'identité et convention signée · Full-service : <strong>aucune caution</strong>.',
      'pkg.note3': '<strong>Sans TVA</strong> — Beamerij est exonéré de TVA. Le prix affiché est le prix que vous payez.',
      'addon.title': 'Options pratiques', 'addon.onrequest': 'Sur demande',
      'addon.1.t': 'Set gaming (PS5)', 'addon.1.d': 'PlayStation 5 avec deux manettes sans fil. FIFA ou Mario Kart sur 200+ inch.',
      'addon.2.t': 'Photographe &amp; vidéaste', 'addon.2.d': 'Un professionnel immortalise votre événement — photos d\'ambiance, photos de groupe ou aftermovie.',
      'addon.3.t': 'Électricité sans prise', 'addon.3.d': 'Batterie puissante et silencieuse pour faire tourner le set partout.',
      'set.title': 'Le contenu du set',
      'set.intro': 'Rien à assembler vous-même : tout est accordé et fonctionne à l\'intérieur comme à l\'extérieur.',
      'set.i1': 'Écran de projection gonflable de 200+ inch avec souffleur silencieux',
      'set.i2': 'Projecteur laser 4K de 5.700 lumens — lumineux, même au crépuscule',
      'set.i3': 'Set audio puissant avec tout le câblage nécessaire',
      'set.i4': 'Supports, câbles et télécommande',
      'set.i5': 'Pour jardin, terrasse, salon, salle des fêtes ou bureau',
      'set.weather': '<strong>Bon à savoir :</strong> les installations extérieures dépendent de la météo. En cas de pluie ou de vent fort, nous cherchons ensemble une solution sûre à temps. Veillez aussi à ce que l\'endroit soit suffisamment sombre — moins il y a de lumière, plus l\'image est belle.',
      'occ.title': 'Pour le match, une soirée cinéma, du gaming ou une fête',
      'occ.intro': 'Pour usage privé et événements d\'entreprise internes, à l\'intérieur ou dehors. Voici les occasions les plus populaires.',
      'occ.tag': 'Mondial 2026 · en cours',
      'occ.1.t': 'Football &amp; Coupe du Monde 2026', 'occ.1.d': 'Le match sur grand écran, sur votre terrasse ou dans le jardin.',
      'occ.2.t': 'Cinéma de jardin &amp; soirées film', 'occ.2.d': 'Un cinéma en plein air pour la famille, les amis ou toute la rue.',
      'occ.3.t': 'Gaming &amp; esports', 'occ.3.d': 'FIFA, Mario Kart ou des courses sur 200+ inch — PS5 en option.',
      'occ.4.t': 'Mariages &amp; fêtes', 'occ.4.d': 'Photos, vidéos et images d\'ambiance pour vos invités.',
      'occ.5.t': 'Événements d\'entreprise', 'occ.5.d': 'Présentations, town halls et fêtes du personnel, en interne chez vous.',
      'occ.6.t': 'Sport au jardin', 'occ.6.d': 'Champions League, le Ronde ou le Tour — supporter ensemble.',
      'occ.foot': 'Aussi pour une communion ou fête laïque, un anniversaire, la fin d\'année ou un home cinéma dans le salon. <a href="#contact" class="text-link">Parlez-nous de votre projet</a>',
      'proc.title': 'Comment ça marche',
      'proc.1.t': 'Demandez votre date', 'proc.1.d': 'Via le formulaire, WhatsApp ou téléphone. Vous savez vite si votre date est libre.',
      'proc.2.t': 'Recevez votre proposition', 'proc.2.d': 'Un prix total clair avec tous les arrangements pratiques.',
      'proc.3.t': 'Nous livrons et installons', 'proc.3.d': 'Ou vous retirez le set vous-même. L\'installation prend 30 à 60 minutes.',
      'proc.4.t': 'Vous profitez, nous rangeons', 'proc.4.d': 'Après votre événement, nous reprenons tout, ou vous rapportez simplement le set.',
      'proc.cta': 'Demandez votre date',
      'wk.kicker': 'Mondial 2026 · jusqu\'au 19 juillet',
      'wk.title': 'Le prochain match sur un écran de 200+ inch',
      'wk.copy': 'Quarts, demi-finales, la finale : offrez-vous l\'ambiance du stade dans votre jardin ou sur votre terrasse. Les dates de week-end partent le plus vite — vérifiez la vôtre à temps.',
      'wk.cta': 'Réservez votre matchday',
      'area.title': 'Livraison à Anvers et alentours',
      'area.copy': 'Livraison et installation full-service à Anvers et jusqu\'à environ 15 km. Le retrait est toujours possible. Votre lieu est plus loin ? Envoyez un message et nous verrons ce qui est possible.',
      'faq.title': 'Questions fréquentes',
      'faq.intro': 'Votre question n\'y figure pas ? Envoyez-nous un message.',
      'faq.link': 'Posez votre question',
      'faq.1.q': 'Livrez-vous aussi ?',
      'faq.1.a': 'Oui. En full-service, nous livrons, installons et reprenons à Anvers et dans les communes environnantes. La livraison est aussi possible en option avec les autres formules.',
      'faq.2.q': 'Combien de temps dure l\'installation ?',
      'faq.2.a': 'Comptez généralement 30 à 60 minutes, selon le lieu et la configuration souhaitée. Nous planifions toujours cela bien avant le début de votre événement.',
      'faq.3.q': 'Que se passe-t-il s\'il pleut ou s\'il vente fort ?',
      'faq.3.a': 'La sécurité avant tout. En cas de météo défavorable, nous envisageons au préalable une alternative en intérieur, un nouveau moment ou une autre solution adaptée.',
      'faq.4.q': 'Comment fonctionne la caution ?',
      'faq.4.a': 'La caution s\'élève à € 300–400 pour le projecteur seul et à € 500–750 pour le full set. Dans certains cas, cela peut aussi se faire avec une carte d\'identité et une convention signée. Vous choisissez la formule full-service, avec livraison et utilisation sur place ? Dans ce cas, aucune caution n\'est demandée.',
      'faq.5.q': 'Que se passe-t-il en cas de dommage, perte ou vol ?',
      'faq.5.a': 'Le locataire est responsable du set depuis la réception jusqu\'à la reprise. Les dommages, pertes ou vols sont décomptés conformément aux conditions de location.',
      'faq.6.q': 'Puis-je annuler ?',
      'faq.6.a': 'C\'est possible selon les modalités de nos conditions générales. Comme nous réservons une date pour vous, des frais d\'annulation peuvent s\'appliquer lorsque l\'annulation intervient peu avant l\'événement.',
      'faq.7.q': 'Le set fonctionne-t-il en intérieur et en extérieur ?',
      'faq.7.a': 'Oui. Un jardin ou une terrasse, c\'est magnifique, mais nous réalisons aussi une projection impressionnante dans un salon, une salle des fêtes ou un espace de bureau. Nous adaptons l\'installation à votre espace.',
      'faq.8.q': 'De quoi avez-vous besoin en matière d\'électricité ?',
      'faq.8.a': 'Une prise normale et sûre à proximité suffit généralement. Faites-nous savoir au préalable si la distance est grande ou s\'il n\'y a pas d\'alimentation électrique sur place — nous apportons alors une station d\'alimentation (batterie) silencieuse pour que votre show ait tout de même lieu.',
      'contact.title': 'Vérifiez votre date',
      'contact.copy': 'Remplissez le formulaire et vous saurez vite si votre date est encore libre — avec une proposition concrète à la clé. Appeler ou envoyer un WhatsApp, c\'est possible aussi.',
      'contact.phone': 'Appelez le <b>0485&nbsp;06&nbsp;69&nbsp;91</b>',
      'contact.response': 'Réponse généralement sous 1 jour ouvrable.',
      'contact.a1': 'Gratuit et sans engagement',
      'contact.a2': 'Prix final sans TVA — pas de surprises',
      'contact.a3': 'Conseil adapté à votre lieu',
      'form.name': 'Nom',
      'form.email': 'E-mail',
      'form.phone': 'Téléphone',
      'form.date': 'Date de l\'événement',
      'form.datehint': 'Pas encore sûr ? Indiquez volontiers une date indicative.',
      'form.location': 'Lieu / code postal',
      'form.package': 'Formule souhaitée',
      'form.choose': 'Choisissez une formule',
      'form.unsure': 'Je ne suis pas encore sûr',
      'form.message': 'Parlez-nous brièvement de votre événement',
      'form.placeholder': 'Par exemple : soirée cinéma pour 25 personnes, installation au jardin…',
      'form.consent': 'En envoyant, vous acceptez notre <a href="privacybeleid.html">politique de confidentialité</a>.',
      'form.submit': 'Demander un devis sans engagement',
      'form.successtitle': 'Merci pour votre demande.',
      'form.successbody': 'Vous aurez généralement de nos nouvelles sous 1 jour ouvrable. Besoin rapide — par exemple pour un match de la Coupe du Monde ce week-end ? Envoyez-nous volontiers un <a href="https://wa.me/32485066991?text=Hoi%20Beamerij%2C%20ik%20heb%20net%20een%20aanvraag%20gedaan%20en%20het%20is%20wat%20dringend." target="_blank" rel="noopener noreferrer">WhatsApp</a>.',
      'form.sending': 'Envoi en cours…',
      'form.notconfigured': 'La connexion du formulaire n\'est pas encore configurée. En attendant, écrivez-nous à info@beamerij.be.',
      'form.error': 'L\'envoi a échoué. Réessayez ou écrivez-nous directement à info@beamerij.be.',
      'footer.tagline': 'Location de projecteurs et big screens pour événements privés et événements d\'entreprise internes, depuis Anvers.',
      'footer.cta': 'Demander un devis',
      'footer.nav': 'Navigation', 'footer.book': 'Demander une date',
      'footer.region': 'Région', 'footer.regionbody': 'Anvers + 15 km<br>Au-delà sur demande',
      'footer.vat': 'Petite entreprise soumise au régime de la franchise de la TVA - TVA non applicable.',
      'footer.privacy': 'Politique de confidentialité',
      'footer.cookies': 'Politique en matière de cookies',
      'footer.terms': 'Conditions générales',
      'footer.cookieprefs': 'Préférences de cookies',
      'footer.rights': 'Tous droits réservés.',
      'float.aria': 'Envoyez un message WhatsApp à Beamerij', 'float.chat': 'Discutez avec nous',
      'totop.aria': 'Retour en haut'
    },
    en: {
      'meta.title': 'Beamerij | Rent a projector & big screen in Antwerp — 4K big-screen rental',
      'meta.desc': 'Beamerij rents premium 4K projectors, a 200+ inch projection screen and complete big-screen sets in Antwerp and surroundings. For movie nights, football, gaming, weddings and corporate events. Delivery and setup available.',
      'skip': 'Skip to content',
      'announce.aria': 'World Cup 2026 — check your date',
      'announce.text': '<b>World Cup&nbsp;2026 is on</b> — every match on a 6-metre screen, right in your garden.',
      'announce.cta': 'Check your date →',
      'nav.menu': 'Open menu',
      'nav.packages': 'Packages &amp; prices',
      'nav.set': 'The set',
      'nav.occasions': 'Occasions',
      'nav.how': 'How it works',
      'nav.faq': 'FAQ',
      'nav.contact': 'Contact',
      'nav.callaria': 'Call Beamerij',
      'nav.cta': 'Request a quote',
      'hero.title': 'Rent a projector and big screen in Antwerp',
      'hero.copy': 'A complete 4K set: 200+ inch inflatable screen, laser projector and sound. Pick it up yourself or have it delivered and set up — for a movie night, the match, a party or a company event.',
      'hero.price': 'Projector only from <strong>€ 70</strong>, complete set from <strong>€ 175</strong> per night. All-inclusive, no VAT.',
      'hero.trust1': '200+ inch inflatable screen',
      'hero.trust2': '4K laser projector, 5,700 lumen',
      'hero.trust3': 'Sound set and all cables included',
      'hero.trust4': 'Delivery and setup available',
      'quick.label': 'Your event date',
      'quick.cta': 'Check availability',
      'quick.note': 'Free and no obligation · usually a reply within 1 working day',
      'quick.wa': 'or send us a WhatsApp',
      'strip.1.t': 'One final price',
      'strip.1.d': 'VAT-exempt and all-inclusive. The price you see is what you pay.',
      'strip.2.t': 'Delivery &amp; setup',
      'strip.2.d': 'We deliver and set up in and around Antwerp. Pickup is possible too.',
      'strip.3.t': 'Works anywhere',
      'strip.3.d': 'Indoors or out, with or without a socket — quiet power station optional.',
      'strip.4.t': 'Fast reply',
      'strip.4.d': 'You usually know within one working day whether your date is free.',
      'pkg.title': 'Packages and prices',
      'pkg.intro': 'All prices are final and VAT-exempt. Rent just the projector or have everything taken care of.',
      'pkg.from': 'from', 'pkg.night': '/ night', 'pkg.featured': 'Most chosen',
      'pkg.avail': 'Check availability', 'pkg.quote': 'Request your quote', 'pkg.discuss': 'Discuss your event',
      'pkg.1.t': 'Projector only', 'pkg.1.d': 'If you already have a screen or a white wall.', 'pkg.1.sub': '€ 100 for a whole weekend', 'pkg.1.f1': '4K laser projector', 'pkg.1.f2': 'Cables and remote control', 'pkg.1.f3': 'Pickup and return by appointment',
      'pkg.2.t': 'Full big-screen set', 'pkg.2.d': 'Screen, picture and sound — your own open-air cinema.', 'pkg.2.sub': '€ 250 for a whole weekend', 'pkg.2.f1': '200+ inch inflatable screen with quiet blower', 'pkg.2.f2': '4K laser projector, sound set and stands', 'pkg.2.f3': 'Clear instructions for setting up',
      'pkg.3.t': 'Full-service event', 'pkg.3.d': 'We deliver, set up and pick up again. You do nothing.', 'pkg.3.sub': 'Antwerp + 15 km', 'pkg.3.f1': 'Everything from the full set', 'pkg.3.f2': 'Delivery, setup and pickup included', 'pkg.3.f3': 'Operation during your event', 'pkg.3.f4': 'No deposit required',
      'pkg.4.t': 'Business &amp; multi-day', 'pkg.4.d': 'For internal company events and multi-day rentals.', 'pkg.4.sub': 'custom quote', 'pkg.4.f1': 'Technical alignment beforehand', 'pkg.4.f2': 'Flexible rental period', 'pkg.4.f3': 'Support during the event possible',
      'pkg.note1': '<strong>Extras</strong> — Delivery, setup &amp; pickup € 50–80 · On-site operator (package A &amp; B) € 100–125 · Extra speaker or cabling € 15–25',
      'pkg.note2': '<strong>Deposit</strong> — Projector € 300–400 · Full set € 500–750, or with an ID card and signed agreement · Full-service: <strong>no deposit</strong>.',
      'pkg.note3': '<strong>No VAT</strong> — Beamerij is VAT-exempt. The price you see is the price you pay.',
      'addon.title': 'Handy options', 'addon.onrequest': 'On request',
      'addon.1.t': 'Gaming set (PS5)', 'addon.1.d': 'PlayStation 5 with two wireless controllers. FIFA or Mario Kart on 200+ inch.',
      'addon.2.t': 'Photographer &amp; videographer', 'addon.2.d': 'A professional captures your event — mood shots, group photos or an aftermovie.',
      'addon.3.t': 'Power without a socket', 'addon.3.d': 'Quiet, powerful power station (battery) so the set can run anywhere.',
      'set.title': 'What\'s in the set',
      'set.intro': 'No hunting for loose parts: everything is matched and works both indoors and outdoors.',
      'set.i1': '200+ inch inflatable projection screen with quiet blower',
      'set.i2': '4K laser projector of 5,700 lumen — bright, even at dusk',
      'set.i3': 'Powerful sound set with all the cabling you need',
      'set.i4': 'Stands, cables and remote control',
      'set.i5': 'Suitable for garden, terrace, living room, function room or office',
      'set.weather': '<strong>Good to know:</strong> outdoor setups depend on the weather. In case of rain or strong wind, we find a safe solution together in good time. Also make sure the spot is dark enough — the less light, the better the picture.',
      'occ.title': 'For the match, a movie night, gaming or a party',
      'occ.intro': 'For private use and internal company events, indoors or out. These are the most popular occasions.',
      'occ.tag': 'World Cup 2026 · on now',
      'occ.1.t': 'Football &amp; World Cup 2026', 'occ.1.d': 'The match on a big screen on your terrace or in your garden.',
      'occ.2.t': 'Garden cinema &amp; movie nights', 'occ.2.d': 'Open-air cinema for family, friends or the whole street.',
      'occ.3.t': 'Gaming &amp; esports', 'occ.3.d': 'FIFA, Mario Kart or racing games on 200+ inch — PS5 available.',
      'occ.4.t': 'Weddings &amp; celebrations', 'occ.4.d': 'Photos, videos and mood visuals for your guests.',
      'occ.5.t': 'Company events', 'occ.5.d': 'Presentations, town halls and staff parties, internally at your place.',
      'occ.6.t': 'Sport in the garden', 'occ.6.d': 'Champions League, the Ronde or the Tour — cheering together.',
      'occ.foot': 'Also for communions, birthdays, year-end parties or a home cinema in the living room. <a href="#contact" class="text-link">Tell us your plan</a>',
      'proc.title': 'How it works',
      'proc.1.t': 'Request your date', 'proc.1.d': 'Via the form, WhatsApp or phone. You quickly hear whether your date is free.',
      'proc.2.t': 'Receive your proposal', 'proc.2.d': 'One clear total price with all the practical arrangements.',
      'proc.3.t': 'We deliver and set up', 'proc.3.d': 'Or you pick up the set yourself. Setup takes about 30 to 60 minutes.',
      'proc.4.t': 'You enjoy, we clean up', 'proc.4.d': 'After your event we pick everything up again, or you simply bring the set back.',
      'proc.cta': 'Request your date',
      'wk.kicker': 'World Cup 2026 · until 19 July',
      'wk.title': 'The next match on a 200+ inch screen',
      'wk.copy': 'Quarter-finals, semi-finals, the final: bring the stadium feeling to your garden or terrace. Weekend dates go fastest — check yours in time.',
      'wk.cta': 'Book your matchday',
      'area.title': 'Delivery in Antwerp and surroundings',
      'area.copy': 'Full-service delivery and setup in Antwerp and up to about 15 km around it. Pickup is always possible. Located further away? Send us a message and we\'ll see what\'s possible.',
      'faq.title': 'Frequently asked questions',
      'faq.intro': 'Don\'t see your question? Send us a message.',
      'faq.link': 'Ask your question',
      'faq.1.q': 'Do you deliver too?',
      'faq.1.a': 'Yes. With full-service we deliver, set up and pick up in Antwerp and the surrounding municipalities. Delivery is also available as an extra with the other packages.',
      'faq.2.q': 'How long does setup take?',
      'faq.2.a': 'Generally count on 30 to 60 minutes, depending on the location and the setup you want. We always plan this well ahead of the start of your event.',
      'faq.3.q': 'What if it rains or the wind picks up?',
      'faq.3.a': 'Safety comes first. In unsuitable weather we look in advance at an indoor alternative, a new date or another fitting solution.',
      'faq.4.q': 'How does the deposit work?',
      'faq.4.a': 'The deposit is € 300–400 for the projector only and € 500–750 for the full set. In some cases this can also be done with an ID card and a signed agreement. If you book the full-service package, with delivery and operation on site, there is no deposit at all.',
      'faq.5.q': 'What about damage, loss or theft?',
      'faq.5.a': 'The renter is responsible for the set from receipt until pickup. Damage, loss or theft is settled according to the rental terms.',
      'faq.6.q': 'Can I cancel?',
      'faq.6.a': 'You can, in line with the terms in our general conditions. Because we reserve a date for you, cancellation fees may apply when the cancellation happens close to the event.',
      'faq.7.q': 'Can the set be used indoors and outdoors?',
      'faq.7.a': 'Yes. A garden or terrace is lovely, but we create an impressive projection in a living room, function room or office space too. We tailor the setup to your space.',
      'faq.8.q': 'What do you need in terms of power?',
      'faq.8.a': 'A normal, safe socket nearby is usually enough. Let us know in advance if the distance is large or if there\'s no power supply at the location — we\'ll then bring a quiet power station (battery) so your show can still go ahead.',
      'contact.title': 'Check your date',
      'contact.copy': 'Fill in the form and you\'ll quickly know whether your date is still free — with a concrete proposal to go with it. Calling or WhatsApping works too.',
      'contact.phone': 'Call <b>0485&nbsp;06&nbsp;69&nbsp;91</b>',
      'contact.response': 'Usually a reply within 1 working day.',
      'contact.a1': 'Free and no obligation',
      'contact.a2': 'Final price without VAT — no surprises',
      'contact.a3': 'Advice tailored to your location',
      'form.name': 'Name',
      'form.email': 'Email',
      'form.phone': 'Phone',
      'form.date': 'Event date',
      'form.datehint': 'Not sure yet? Feel free to give a rough date.',
      'form.location': 'Location / postcode',
      'form.package': 'Preferred package',
      'form.choose': 'Choose a package',
      'form.unsure': 'I\'m not sure yet',
      'form.message': 'Tell us a little about your event',
      'form.placeholder': 'For example: movie night for 25 people, setup in the garden…',
      'form.consent': 'By submitting you agree to our <a href="privacybeleid.html">privacy policy</a>.',
      'form.submit': 'Request a no-obligation quote',
      'form.successtitle': 'Thanks for your request.',
      'form.successbody': 'You\'ll usually hear from us within 1 working day. Need it fast — for a World Cup match this weekend, say? Feel free to send us a <a href="https://wa.me/32485066991?text=Hoi%20Beamerij%2C%20ik%20heb%20net%20een%20aanvraag%20gedaan%20en%20het%20is%20wat%20dringend." target="_blank" rel="noopener noreferrer">WhatsApp</a>.',
      'form.sending': 'Just sending…',
      'form.notconfigured': 'The form connection isn\'t set up yet. In the meantime, email us at info@beamerij.be.',
      'form.error': 'Sending didn\'t work. Please try again or email us directly at info@beamerij.be.',
      'footer.tagline': 'Projector and big-screen rental for private and internal company events, based in Antwerp.',
      'footer.cta': 'Request a quote',
      'footer.nav': 'Navigation', 'footer.book': 'Request a date',
      'footer.region': 'Region', 'footer.regionbody': 'Antwerp + 15 km<br>Beyond that on request',
      'footer.vat': 'Small business subject to the VAT exemption scheme - VAT not applicable.',
      'footer.privacy': 'Privacy policy',
      'footer.cookies': 'Cookie policy',
      'footer.terms': 'General conditions',
      'footer.cookieprefs': 'Cookie preferences',
      'footer.rights': 'All rights reserved.',
      'float.aria': 'Send Beamerij a WhatsApp message', 'float.chat': 'Chat with us',
      'totop.aria': 'Back to top'
    }
  };

  function getInitial() {
    try { var s = localStorage.getItem(STORE); if (s && SUPPORTED.indexOf(s) > -1) return s; } catch (e) {}
    try { var u = new URLSearchParams(location.search).get('lang'); if (u && SUPPORTED.indexOf(u) > -1) return u; } catch (e) {}
    var b = (navigator.language || 'nl').slice(0, 2).toLowerCase();
    return SUPPORTED.indexOf(b) > -1 ? b : 'nl';
  }

  var current = 'nl';
  function val(key) { var d = DICT[current] || {}; return d[key] != null ? d[key] : DICT.nl[key]; }

  function apply(lang) {
    current = SUPPORTED.indexOf(lang) > -1 ? lang : 'nl';
    document.querySelectorAll('[data-i18n]').forEach(function (el) { var v = val(el.getAttribute('data-i18n')); if (v != null) el.innerHTML = v; });
    document.querySelectorAll('[data-i18n-ph]').forEach(function (el) { var v = val(el.getAttribute('data-i18n-ph')); if (v != null) el.setAttribute('placeholder', v); });
    document.querySelectorAll('[data-i18n-al]').forEach(function (el) { var v = val(el.getAttribute('data-i18n-al')); if (v != null) el.setAttribute('aria-label', v); });
    var titleKey = document.documentElement.getAttribute('data-i18n-title') || 'meta.title';
    if (val(titleKey)) document.title = val(titleKey);
    var descKey = document.documentElement.getAttribute('data-i18n-desc') || 'meta.desc';
    var md = document.querySelector('meta[name="description"]'); if (md && val(descKey)) md.setAttribute('content', val(descKey));
    document.documentElement.setAttribute('lang', current === 'nl' ? 'nl-BE' : current);
    document.querySelectorAll('[data-lang]').forEach(function (b) { b.setAttribute('aria-pressed', String(b.getAttribute('data-lang') === current)); });
    window.__lang = current;
  }
  window.t = function (key) { return val(key) || ''; };

  /* let a per-page script (e.g. legal-i18n.js) add extra translations, then re-render */
  window.__i18nAddDict = function (extra) {
    if (!extra) return;
    SUPPORTED.forEach(function (l) {
      if (!extra[l]) return;
      var d = DICT[l] || (DICT[l] = {});
      for (var k in extra[l]) if (Object.prototype.hasOwnProperty.call(extra[l], k)) d[k] = extra[l][k];
    });
    apply(current);
  };

  var reduced = false;
  try { reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches; } catch (e) {}

  function set(lang) {
    if (SUPPORTED.indexOf(lang) < 0) return;
    try { localStorage.setItem(STORE, lang); } catch (e) {}
    if (reduced || lang === current) { apply(lang); return; }
    document.body.classList.add('lang-switching');           // fade + blur current text out
    window.setTimeout(function () {
      apply(lang);                                           // swap text while hidden
      window.requestAnimationFrame(function () {             // next frame: fade back in
        document.body.classList.remove('lang-switching');
      });
    }, 240);
  }
  window.__setLang = set;
  document.addEventListener('click', function (e) {
    var b = e.target.closest && e.target.closest('[data-lang]');
    if (!b) return;
    e.preventDefault();
    set(b.getAttribute('data-lang'));
  });

  apply(getInitial());
})();
